#ifndef APP_STATE_H
#define APP_STATE_H

enum AppState {
  STATE_MAIN_MENU,
  STATE_ALARM_MENU,
  STATE_ANIMATION_MENU,
  STATE_BRIGHTNESS_MENU,
  STATE_TEMPERATURE_COLOR,
  STATE_SHOW_TIME
};

#endif
